/**
 * WheelRing.java - Group 34 (Wheel of Fortune) v2 items A/B/F.
 *
 * The wheel's ring: the geometry every other class measures against, the per-spin sample of prizes, and the
 * two display-entity layers that make up the wheel face —
 *   - the FACE: one ITEM_DISPLAY showing the baked {@code customblocks:wheel_face} texture, a disc of
 *     {@link #SLICES} carnival wedges in unique fully-saturated colours, spawned once and never touched again;
 *   - {@link #SLICES} prize ICONS drawn in their inventory look on top of the face, RE-ROLLED on every spin
 *     from a fresh random sample of the cached pool (design lock 2026-07-23).
 *
 * Geometry note (the whole package depends on it): the wheel is VERTICAL and turned to face the placer, so
 * its plane is spanned by world-up and one horizontal axis. Everything is expressed in the display entities'
 * own local frame at yaw {@code faceYaw}: local +X is {@link #axisX} (the in-plane horizontal), local +Y is
 * world up, local +Z is {@link #normal} (out of the wheel, toward the viewer). That frame is right-handed, so a
 * viewer out front sees +X to their right and angles running counter-clockwise — which is why the arrow can be
 * aimed with a single rotation about local Z ({@link WheelDisplayVisual#quatZ}) and why the baked face's
 * texture, laid out in that same convention, lines up slice-for-slice with the icons.
 *
 * Depends on: WheelPool (the cached prize list), WheelDisplayVisual (shared nbt builders)
 * Called by:  WheelBlockEntity (build on place, reroll per spin), WheelDisplayVisual (geometry)
 */
package com.customblocks.wheel;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.decoration.DisplayEntity;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.random.Random;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public final class WheelRing {

    private WheelRing() {} // static-only

    // ------------------------------------------------------------------ ring geometry (design locks)
    /** Slices = visible prizes per spin AND wedge count. 50 (owner lock 2026-07-23): chunky readable wedges,
     *  one unique colour each. The full ~1300 pool stays reachable — every spin re-rolls a fresh 50. */
    public static final int SLICES = 50;
    /** Outer rim radius — the wheel measures ~20 blocks across. */
    public static final double OUTER_R = 10.0;
    /** Inner edge of the ICON band. Icons ring the rim here; the wedges fill the whole disc behind them. */
    public static final double INNER_R = 6.0;
    /** Where the prize icons sit: the middle of the icon band, near the rim. */
    public static final double ICON_R = (OUTER_R + INNER_R) / 2.0;
    /** Degrees one slice spans. */
    public static final double SLICE_DEG = 360.0 / SLICES;

    /**
     * How the face is built (owner lock 2026-07-24, replacing the strip stacks — and the tapered bands before
     * them).
     *
     * <p>The face is ONE quad wearing a BAKED texture, {@code customblocks:block/wheel_face}, generated by
     * {@code tools/gen_wheel_face.py}. Both earlier builds tried to assemble the disc out of rectangles in
     * game; both stair-stepped, because a rectangle cannot be clipped along a ray and the only way to hide the
     * overhang is to paint the next slice exactly on top of it. Minecraft will not promise that: the quads are
     * translucent TEXT_DISPLAY backgrounds separated by 0.002 blocks, and that ordering does not survive
     * translucent rendering. A raster has no ordering to lose — the generator assigns every texel to exactly
     * one slice, so a wedge boundary is a true straight ray and the seam cannot open, flicker or step.
     *
     * <p>The texture's slice rule is {@code floor(angle / SLICE_DEG + 0.5) mod SLICES}, the same rule
     * {@link #sliceAt} uses to name the winner, so the colour the arrow stops over is the slice the code
     * awards, by construction.
     */
    /** Baked face texture size, and the clear border inside it. Both MUST match {@code tools/gen_wheel_face.py}
     *  — the disc's radius in the PNG is {@code FACE_TEX_PX / 2 - FACE_MARGIN_PX}, and {@link #FACE_SCALE}
     *  inverts exactly that to land the rim on {@link #OUTER_R}. */
    private static final double FACE_TEX_PX = 1024.0;
    private static final double FACE_MARGIN_PX = 8.0;
    /** Scale for the face ITEM_DISPLAY. The model spans the WHOLE texture across one block, the disc covers all
     *  but the margin, so blowing the quad up by this puts the painted rim exactly on {@link #OUTER_R}. */
    private static final double FACE_SCALE = 2.0 * OUTER_R * FACE_TEX_PX / (FACE_TEX_PX - 2.0 * FACE_MARGIN_PX);

    /** Prize icon scale — comfortably under one 50-slice arc, so the icons ring the wheel without smearing. */
    private static final float ICON_SCALE = 0.85f;

    // ------------------------------------------------------------------ geometry helpers

    /** The wheel's centre point (the hidden anchor block's centre). */
    public static Vec3d center(BlockPos anchor) {
        return Vec3d.ofCenter(anchor);
    }

    /** Out of the wheel face, toward whoever placed it — the display entities' local +Z at {@code faceYaw}. */
    public static Vec3d normal(float faceYaw) {
        double r = Math.toRadians(faceYaw);
        return new Vec3d(-Math.sin(r), 0, Math.cos(r));
    }

    /** The in-plane horizontal axis — the display entities' local +X at {@code faceYaw} (wheel angle 0). */
    public static Vec3d axisX(float faceYaw) {
        double r = Math.toRadians(faceYaw);
        return new Vec3d(Math.cos(r), 0, Math.sin(r));
    }

    /** A point on the wheel: {@code radius} out at {@code angleDeg}, pushed {@code depth} toward the viewer. */
    public static Vec3d point(BlockPos anchor, float faceYaw, double radius, double angleDeg, double depth) {
        double a = Math.toRadians(angleDeg);
        return center(anchor)
                .add(axisX(faceYaw).multiply(radius * Math.cos(a)))
                .add(0, radius * Math.sin(a), 0)
                .add(normal(faceYaw).multiply(depth));
    }

    /** The centre angle of slice {@code i}. */
    public static double sliceCenterDeg(int i) {
        return i * SLICE_DEG;
    }

    /** The slice an angle points INTO — this is what turns the arrow's final angle into the winner (item C). */
    public static int sliceAt(double angleDeg) {
        double norm = ((angleDeg % 360.0) + 360.0) % 360.0;
        return (int) (Math.round(norm / SLICE_DEG) % SLICES);
    }

    // ------------------------------------------------------------------ per-spin sample (item B)

    /**
     * {@code count} DISTINCT prizes drawn at random from the cached pool, by partial Fisher-Yates so no item
     * repeats inside one spin. Called fresh on every spin — that is what keeps all ~1300 items reachable
     * despite the {@link #SLICES}-icon cap.
     */
    public static List<Item> sample(Random random, int count) {
        List<Item> pool = WheelPool.items();
        int n = pool.size();
        int take = Math.min(count, n);
        int[] idx = new int[n];
        for (int i = 0; i < n; i++) idx[i] = i;
        List<Item> out = new ArrayList<>(take);
        for (int i = 0; i < take; i++) {
            int j = i + random.nextInt(n - i);
            int swap = idx[i];
            idx[i] = idx[j];
            idx[j] = swap;
            out.add(pool.get(idx[i]));
        }
        return out;
    }

    // ------------------------------------------------------------------ face layer (spawned once)

    /**
     * Spawn the wheel face: ONE ITEM_DISPLAY carrying the baked wedge disc. Placement only — never touched
     * again, and nothing about it depends on view angle, draw order or depth, so there is nothing left to
     * flicker or tear.
     */
    public static UUID spawnFace(ServerWorld world, BlockPos anchor, float faceYaw) {
        DisplayEntity.ItemDisplayEntity e = new DisplayEntity.ItemDisplayEntity(EntityType.ITEM_DISPLAY, world);
        e.readNbt(faceNbt(anchor, faceYaw));
        world.spawnEntity(e);
        return e.getUuid();
    }

    private static NbtCompound faceNbt(BlockPos anchor, float faceYaw) {
        // Depth 0 — the face IS the wheel plane; icons, arrow and popup all sit in front of it.
        NbtCompound n = WheelDisplayVisual.baseNbt(center(anchor), faceYaw, "fixed");
        n.put("transformation",
                WheelDisplayVisual.transform((float) FACE_SCALE, (float) FACE_SCALE, (float) FACE_SCALE));
        n.put("item", WheelDisplayVisual.itemNbt(WheelBlockRegistry.FACE_ITEM));
        // "none" = the raw model, so the flat quad lies exactly in the wheel plane and its [0,16] model box maps
        // to [-0.5,+0.5] blocks — the disc comes out centred on the anchor before FACE_SCALE blows it up.
        n.putString("item_display", "none");
        return n;
    }

    // ------------------------------------------------------------------ icon layer (re-rolled per spin)

    /** Spawn the prize-icon ring showing {@code items} (one per slice). */
    public static List<UUID> spawnIcons(ServerWorld world, BlockPos anchor, float faceYaw, List<Item> items) {
        List<UUID> out = new ArrayList<>(SLICES);
        for (int i = 0; i < SLICES; i++) {
            DisplayEntity.ItemDisplayEntity e = new DisplayEntity.ItemDisplayEntity(EntityType.ITEM_DISPLAY, world);
            e.readNbt(iconNbt(anchor, faceYaw, i, itemAt(items, i)));
            world.spawnEntity(e);
            out.add(e.getUuid());
        }
        return List.copyOf(out);
    }

    /** Re-draw the whole icon ring with a fresh sample — one push per slice, once per spin. */
    public static void pushIcons(ServerWorld world, List<UUID> icons, BlockPos anchor, float faceYaw, List<Item> items) {
        for (int i = 0; i < icons.size(); i++) {
            UUID id = icons.get(i);
            if (id == null || !(world.getEntity(id) instanceof DisplayEntity.ItemDisplayEntity e)) continue;
            NbtCompound n = iconNbt(anchor, faceYaw, i, itemAt(items, i));
            n.putUuid("UUID", id);
            e.readNbt(n);
        }
    }

    private static NbtCompound iconNbt(BlockPos anchor, float faceYaw, int slice, Item item) {
        Vec3d p = point(anchor, faceYaw, ICON_R, sliceCenterDeg(slice), WheelDisplayVisual.DEPTH_ICON);
        NbtCompound n = WheelDisplayVisual.baseNbt(p, faceYaw, "fixed");
        n.put("transformation", WheelDisplayVisual.transform(ICON_SCALE, ICON_SCALE, ICON_SCALE));
        n.put("item", WheelDisplayVisual.itemNbt(item));
        // "gui" = the inventory look: blocks come out isometric like their item icon, flat items stay flat.
        // Icons are NOT rotated with their wedge — upright reads far better across a 20-block ring.
        n.putString("item_display", "gui");
        return n;
    }

    /** The prize on slice {@code i}, tolerating a short/stale list (a reload before the first spin). */
    private static Item itemAt(@Nullable List<Item> items, int i) {
        if (items == null || items.isEmpty()) return Items.STONE; // never a denylisted item on the ring (item F)
        return items.get(i % items.size());
    }
}
